remove ifdef __linux__ because of the error on windows
D:\a\signature\signature\tests\test.cpp(152,5): error C2121: '#': invalid character: possibly the result of a macro expansion [D:\a\signature\signature\build\tests\test_signature.vcxproj]
D:\a\signature\signature\tests\test.cpp(140,5): error C2065: 'ifdef': undeclared identifier [D:\a\signature\signature\build\tests\test_signature.vcxproj]
D:\a\signature\signature\tests\test.cpp(140,5): error C2146: syntax error: missing ';' before identifier '__linux__' [D:\a\signature\signature\build\tests\test_signature.vcxproj]
D:\a\signature\signature\tests\test.cpp(140,5): error C2065: '__linux__': undeclared identifier [D:\a\signature\signature\build\tests\test_signature.vcxproj]